set(PRECOMPILE_HEADERS
    <algorithm>
    <array>
    <chrono>
    <cstdint>
    <cstddef>
    <filesystem>
    <fstream>
    <functional>
    <list>
    <map>
    <memory>
    <mutex>
    <set>
    <string>
    <string_view>
    <stop_token>
    <thread>
    <unordered_map>
    <utility>
    <ranges>
    <variant>
    <vector>
    <boost/asio.hpp>
    <boost/beast.hpp>)
