name: Build Windows MSVC Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Docker image tag'
        required: true
        default: 'v1.0-msvc'

jobs:
  build-and-push:
    name: Build and Push Windows Docker Image
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Windows Docker Image
        run: |
          echo "Building Docker image: ghcr.io/kingofknights/arthur:${{ github.event.inputs.tag }}"
          docker build -f Dockerfile.windows -t ghcr.io/kingofknights/arthur:${{ github.event.inputs.tag }} .

      - name: Push Docker Image to GHCR
        run: |
          echo "Pushing Docker image: ghcr.io/kingofknights/arthur:${{ github.event.inputs.tag }}"
          docker push ghcr.io/kingofknights/arthur:${{ github.event.inputs.tag }}
