name: Linux Build and Deployment

on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubunutu-latest

    steps:
      - name: Update OS
        run: |
          sudo apt update -y 
          sudo apt install libboost-all-dev

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build with CMake
        run: cmake --build build --config ${{env.BUILD_TYPE}}
