name: Windows Build and Deployment

on:
  push:
    branches: [ "workflow" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update submodule
        run: |
          git submodule init
          git submodule update --recursive --remote

      - name: Install boost
        run: choco install boost-msvc-14.3 --version=1.78.0

      - name: Configure Arthur
        working-directory: ${{github.workspace}}/
        run: cmake -B build -DFMT_UNICODE=0

      - name: Build Arthur
        working-directory: ${{github.workspace}}/
        run: cmake --build build
