name: Windows Build and Deployment

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["workflow"]
env:
  BUILD_TYPE: Release
  BOOST_PRE_DOWNLOAD_LINK: "https://boost.teeks99.com/bin/1.78.0/boost_1_78_0-msvc-14.3-64.exe"
  TOOLCHAIN_FILE: C:\vcpkg\scripts\buildsystems\vcpkg.cmake

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Download boost
        run: Invoke-WebRequest -Uri ${{env.BOOST_PRE_DOWNLOAD_LINK}} -OutFile  "boost_installer.exe"

      - name: Install Boost
        run: Start-Process -FilePath "boost_installer.exe" -ArgumentList "/VERYSILENT" -Wait

      - name: Configure Arthur
        working-directory: ${{github.workspace}}/
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{env.TOOLCHAIN_FILE}} -DCMAKE_GENERATOR=Ninja -DCMAKE_MAKE_PROGRAM=ninja

      - name: Build Arthur
        working-directory: ${{github.workspace}}/
        run: cmake --build build --config ${{env.BUILD_TYPE}} --target install

      - name: Compress the artifact
        working-directory: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
        run: tar -czvf artifact.tar *.exe *.ttf setting.json
        continue-on-error: true

      - name: Release artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/artifact.tar
          name: Releases
